### PR TITLE
hide inlined frames

### LINKED ISSUE #118: ValueTaskAwaiter no longer annotated with StackTraceHidden
Running against .NET 5, the test `MixedStack` fails as a new frame shows up:

`TResult System.Runtime.CompilerServices.ValueTaskAwaiter<TResult>.GetResult()`.

In [this change to the runtime (corefx)](https://github.com/dotnet/coreclr/pull/14652) you've added the attributes but it seems like [it's are gone now](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/ValueTaskAwaiter.cs#L44).

The current approach is to either rely on the attribute or fallback to the type checks:
https://github.com/benaadams/Ben.Demystifier/blob/87375e9013db462ad5af21bc308bc73c63cfe919/src/Ben.Demystifier/EnhancedStackTrace.Frames.cs#L665-L703

I could open a PR that removes the `if` and tries both strategies. Let me know if this is the approach you want to take, or another?

### PR DESCRIPTION
**Pull request by bruno-garcia**
Resolves: #118

Since you put the runtime to check first for `AggressiveInlining` and after that to the `StackTraceHiddenAttribute`, I've lifted the latter to the top to keep the same sequence. The rest of the checks stayed as they were. Let me know if this works for you.

Regarding testing against .NET 5:
* A few tests break so would need some changes in behavior.
* `net46` on Mono (I'm on a mac) also fails even without any changes. Is there a goal to make it pass there?
* The repo AppVeyor build seems broken. Is there an interest to move to GH actions?

### CODE REVIEW

**Comment by benaadams** [comment]
> A few tests break so would need some changes in behavior.

This is ok; less is more :)

> `net46` on Mono (I'm on a mac) also fails even without any changes. Is there a goal to make it pass there?

Would be happy if it did :)

> The repo AppVeyor build seems broken. Is there an interest to move to GH actions?

Very much; I was just reading the docs; but am not very familiar with it. Still at mostly pressing the "template" buttons stage with other projects

**Comment by bruno-garcia** [comment]
I've got GH actions on a few repos so I might be able to help on this.

Let's see during the week. I don't like to promise because time is short and I've got some hobby projects ([one which involved copying a bunch of ur code, wanted to let you know](https://github.com/bruno-garcia/simbolo/tree/main/Simbolo/StackFrameData/Ben)).

**Comment by benaadams** [comment]
Thank you!

**Comment by benaadams** [comment]
Updated the tests for new frameworks

**Comment by benaadams** [comment]
Also added GitHub testing https://github.com/benaadams/Ben.Demystifier/pull/123

**Comment by bruno-garcia** [comment]
Oh thanks! Just saw all the changes :)
Looking great,thanks!

**Pull request merged**
