### PR TITLE
Resolve #20

### LINKED ISSUE #20: GetParameter throws on Task<object> on GetCustomAttributes<TupleElementNamesAttribute>
```
var tupleNames = parameter.GetCustomAttributes<TupleElementNamesAttribute>().FirstOrDefault()?.TransformNames;
```
Throws an index of out range exception when there are no custom attributes.

Specific type where I saw it was 
```
System.Threading.Tasks.Task`1[[System.Object, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
```

Running on .NET 4.6.2

### PR DESCRIPTION
**Pull request by rgmills**
Not sure if there should be anything else needed that's more nuanced around this.

### CODE REVIEW

**Comment by benaadams** [comment]
Is there a way to catch the failure in a test; and have it pass with the change?

**Comment by rgmills** [comment]
Should be able to. Will take a look tonight and see what I can do.
________________________________

**Comment by benaadams** [comment]
Bit weird `FirstOrDefault()` should have same effect

**Comment by benaadams** [comment]
Merged as https://github.com/benaadams/Ben.Demystifier/pull/23

Would still be interested in repo test case; to make sure it takes care of it and it doesn't regress

**Comment by benaadams** [comment]
Rather merged as https://github.com/benaadams/Ben.Demystifier/pull/24

**Comment by rgmills** [comment]
@benaadams Here's a repro.  It only occurs on full framework, works just fine on netcoreapp2.0

```
public class InheritenceTests
    {
		private abstract class BaseClass
		{
			public abstract Task<object> Method();
		}

		private class ImplClass : BaseClass
		{
			public override Task<object> Method()
			{
				throw new Exception();
			}
		}

		[Fact]
		public async Task ImplementedAbstractMethodDoesNotThrow()
		{
			// Arrange
			var instance = new ImplClass();

			// Act
			Exception exception = null;
			try
			{
				await instance.Method();
			}
			catch (Exception ex)
			{
				exception = ex;
			}

			// Act
			var est = new EnhancedStackTrace(exception);
		}
    }
```

**Comment by benaadams** [comment]
Wow
```
[xUnit.net 00:00:01.2436697]   Finished:    Ben.Demystifier.Test
Failed   Ben.Demystifier.Test.InheritenceTests.ImplementedAbstractMethodDoesNotThrow
Error Message:
 System.IndexOutOfRangeException : Index was outside the bounds of the array.
Stack Trace:
   at System.Attribute.GetParentDefinition(ParameterInfo param)
   at System.Attribute.InternalParamGetCustomAttributes(ParameterInfo param, Type type, Boolean inherit)
   at System.Attribute.GetCustomAttributes(ParameterInfo element, Type attributeType, Boolean inherit)
   at System.Reflection.CustomAttributeExtensions.GetCustomAttributes[T](ParameterInfo element)
   at System.Diagnostics.EnhancedStackTrace.GetParameter(ParameterInfo parameter) in C:\GitHub\Ben.Demystifier\src\Ben.Demystifier\EnhancedStackTrace.Frames.cs:line 527
   at System.Diagnostics.EnhancedStackTrace.GetMethodDisplayString(MethodBase originMethod) in C:\GitHub\Ben.Demystifier\src\Ben.Demystifier\EnhancedStackTrace.Frames.cs:line 175
   at System.Diagnostics.EnhancedStackTrace.GetFrames(StackTrace stackTrace) in C:\GitHub\Ben.Demystifier\src\Ben.Demystifier\EnhancedStackTrace.Frames.cs:line 71
   at System.Diagnostics.EnhancedStackTrace.GetFrames(Exception exception) in C:\GitHub\Ben.Demystifier\src\Ben.Demystifier\EnhancedStackTrace.Frames.cs:line 33
   at System.Diagnostics.EnhancedStackTrace..ctor(Exception e) in C:\GitHub\Ben.Demystifier\src\Ben.Demystifier\EnhancedStackTrace.cs:line 30
   at Ben.Demystifier.Test.InheritenceTests.<ImplementedAbstractMethodDoesNotThrow>d__2.MoveNext() in C:\GitHub\Ben.Demystifier\test\Ben.Demystifier.Test\InheritenceTests.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```
Seems a Framework bug... Nice catch

**Comment by rgmills** [comment]
Thanks to ASP.NET MVC :)

https://github.com/aspnet/AspNetWebStack/blob/62d0b2df0bcca848a8e0848fd1866928df15528e/src/System.Web.Http/Controllers/ReflectedHttpActionDescriptor.cs#L130

**Pull request closed without merging**
