### PR TITLE
Add a unit-test for #109

### PR DESCRIPTION
**Pull request by KirillOsenkov**

### CODE REVIEW

**Comment by benaadams** [comment]
Shouldn't this test fail?

**Comment by KirillOsenkov** [comment]
Oh sorry I forgot :) You’ll see an exception under debugger if you debug with first-chance exceptions enabled.

**Comment by KirillOsenkov** [comment]
Fails for me:
```
Process terminated. Assertion failed.
   at Ben.Demystifier.Test.TypeNameTests.NestedGenericTypes() in C:\Ben.Demystifier\test\Ben.Demystifier.Test\TypeNameTests.cs:line 18
```

**Comment by benaadams** [comment]
Thank you!

**Pull request merged**
