### PR TITLE
build in sentry csproj

### PR DESCRIPTION
**Pull request by bruno-garcia**
Changes I had to make to build and test inside the Sentry SDK.

I'm hoping to clean up the changes here and merge it back upstream, if possible.
I suspect the `strict` flag is what drove some of the changes, unsure yet since it also builds against `net5.0` here.

Sentry PR: https://github.com/getsentry/sentry-dotnet/pull/732

### CODE REVIEW

**Comment by bruno-garcia** [comment]
@benaadams Trying my luck. Any blockers you identify to get this merged?

🙏

**Comment by benaadams** [comment]
Merged

**Comment by benaadams** [comment]
I assume from  getsentry/sentry-dotnet#732 you are using it as a submodule and don't need a numbered NuGet release for this?

**Comment by bruno-garcia** [comment]
Wow thanks @benaadams !

> I assume from getsentry/sentry-dotnet#732 you are using it as a submodule and don't need a numbered NuGet release for this?

Yeah, I'm good! :)

**Pull request merged**
