### PR TITLE
Add namespace to frame conditionally

### PR DESCRIPTION
**Pull request by bruno-garcia**
If I'm not mistaken, adding an optional parameter is technically a breaking change.
I could add an overload so that's not breaking if that's better.

Also, as you might recall, I'm consuming the package via git submodule so no need to publish just because of this change.

🙏

### CODE REVIEW

**Comment by benaadams** [comment]
> If I'm not mistaken, adding an optional parameter is technically a breaking change.

Yeah, should forward the existing method instead?

```csharp
// Forward existing method to introduce the default
public StringBuilder Append(StringBuilder builder)
    => Append(StringBuilder builder, fullName: true)

// New method
public StringBuilder Append(StringBuilder builder, bool fullName)
{
   // ...
```

**Comment by benaadams** [comment]
Might be issues with making the entire public api internal? 😅

**Comment by bruno-garcia** [comment]
lol
@benaadams sorry pushed the wrong thing here :D

**Review by benaadams — APPROVED** [review]

**Comment by benaadams** [comment]
Thank you!

**Comment by bruno-garcia** [comment]
Thank you! :)

**Pull request merged**
